### ISSUE TITLE
Build/Config/Deploy

### ISSUE THREAD

**Issue by stalkermn** [Papka24/base#1]
Hey, guys! 
It would be amazing, if you'll make any spec how to build/configure/deploy this application for ordinary mortal. 
Probably would be great few options for community and others:
1) Docket/Vagrant
3) Console receipt
4) Preconfigured AWS AMI.
5) Puppet/Chef/Ansible (optional)

Ready to help to cover methods described above.
Thanks a lot, waiting for any feedback

**Comment by Papka24** [comment]
Sorry, a little bit later.. Build server is simple "gradle shadowJar", build statics "gradle build" (details you can see in gradle files).

**Comment by SashkaNebesny** [comment]
All the same the description of how to deploy the software would not hurt.

**Comment by VladyslavKurmaz** [comment]
@stalkermn @SashkaNebesny 
Please check https://github.com/Papka24/base/pull/9
or
pull directly from my fork
https://github.com/VladyslavKurmaz/base

**Comment by VladyslavKurmaz** [comment]
You can find docker compose howto inside README file
