### ISSUE TITLE
Howto setup domain key

### ISSUE THREAD

**Issue by VladyslavKurmaz** [Papka24/base#10]
Could you please describe step by step instruction how to fix next issue
![image](https://user-images.githubusercontent.com/1977961/27731097-62ade476-5d94-11e7-95e0-943a466d6026.png)

**Comment by MaximBelov** [comment]
https://www.google.com/recaptcha/admin
add new site


server side
server/src/main/resources/config.properties
recaptcha.secret= 6LeVDiQUAAAAAOdEwex3ygjPJ4jfffffff37iUfo


static-page/src/js/actionLogin.js
CTRL+F - sitekey
client side
sitekey: 6LeVDiQUAAAAADLGrYSjT92fgZJsewYfffffASS,
