### ISSUE TITLE
"Помилка сервера реєстрації 404"

### ISSUE THREAD

**Issue by S1AnGeR** [Papka24/base#12]
Здравствуйте. Я поднял папку 24 на сервере , захожу по localhost ввожу данные , мне выдает: 

Помилка сервера реєстрації 404
![06-08-2017 151224](https://user-images.githubusercontent.com/5192883/29003132-c2914102-7ab9-11e7-9c8e-a5d9febc11c5.png)
подскажите в чем может быть причина? ( в env я внес секреты и ключ reCapcha)

**Comment by S1AnGeR** [comment]
![image](https://user-images.githubusercontent.com/5192883/29003167-5c286494-7aba-11e7-8e4f-1119626f8f4f.png)

**Comment by VladyslavKurmaz** [comment]
Здравствуйте.
Да, это известный баг. Сейчас система сконфигурирована для запуска на Apache в минимальной конфигурации и там нет все редиректов на бэкенд.
...
У меня есть пример nginx конфигурации с боевого сервера и сейчас пробую адаптировать его в docker окружение.
...
Спасибо.

**Comment by SashkaNebesny** [comment]
Скажите, пожалуйста, решена ли проблема с регистрацией? 
При установке я выбрал SERVER_TYPE=nginx, но судя по логам:
`static_1    | 91.219.54.65 - - [11/Aug/2017:19:59:21 +0000] "GET /fonts/fontawesome-webfont.woff HTTP/1.1" 404 571 "http://doc.dts.pp.ua/css/all.css" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
static_1    | 2017/08/11 19:59:21 [error] 5#5: *18 open() "/usr/share/nginx/html/fonts/avenir/AvenirLight.woff" failed (2: No such file or directory), client: 91.219.54.65, server: localhost, request: "GET /fonts/avenir/AvenirLight.woff HTTP/1.1", host: "doc.dts.pp.ua", referrer: "http://doc.dts.pp.ua/css/all.css"
static_1    | 2017/08/11 19:59:21 [error] 5#5: *19 open() "/usr/share/nginx/html/img/fox.png" failed (2: No such file or directory), client: 91.219.54.65, server: localhost, request: "GET /img/fox.png HTTP/1.1", host: "doc.dts.pp.ua", referrer: "http://doc.dts.pp.ua/css/all.css"
static_1    | 91.219.54.65 - - [11/Aug/2017:19:59:21 +0000] "GET /fonts/avenir/AvenirLight.woff HTTP/1.1" 404 571 "http://doc.dts.pp.ua/css/all.css" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
static_1    | 91.219.54.65 - - [11/Aug/2017:19:59:21 +0000] "GET /img/fox.png HTTP/1.1" 404 571 "http://doc.dts.pp.ua/css/all.css" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
static_1    | 2017/08/11 19:59:21 [error] 5#5: *19 open() "/usr/share/nginx/html/img/goodBad.png" failed (2: No such file or directory), client: 91.219.54.65, server: localhost, request: "GET /img/goodBad.png HTTP/1.1", host: "doc.dts.pp.ua", referrer: "http://doc.dts.pp.ua/css/all.css"
static_1    | 91.219.54.65 - - [11/Aug/2017:19:59:21 +0000] "GET /img/goodBad.png HTTP/1.1" 404 571 "http://doc.dts.pp.ua/css/all.css" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
static_1    | 91.219.54.65 - - [11/Aug/2017:19:59:21 +0000] "GET /img/way.png HTTP/1.1" 404 571 "http://doc.dts.pp.ua/css/all.css" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
static_1    | 91.219.54.65 - - [11/Aug/2017:19:59:21 +0000] "GET /img/bonus.png HTTP/1.1" 404 571 "http://doc.dts.pp.ua/css/all.css" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
static_1    | 91.219.54.65 - - [11/Aug/2017:19:59:21 +0000] "GET /img/oneciconcloud.png HTTP/1.1" 404 571 "http://doc.dts.pp.ua/css/all.css" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
static_1    | 91.219.54.65 - - [11/Aug/2017:19:59:21 +0000] "GET /img/onecicon.png HTTP/1.1" 404 571 "http://doc.dts.pp.ua/css/all.css" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
static_1    | 2017/08/11 19:59:21 [error] 5#5: *18 open() "/usr/share/nginx/html/img/way.png" failed (2: No such file or directory), client: 91.219.54.65, server: localhost, request: "GET /img/way.png HTTP/1.1", host: "doc.dts.pp.ua", referrer: "http://doc.dts.pp.ua/css/all.css"
static_1    | 2017/08/11 19:59:21 [error] 5#5: *14 open() "/usr/share/nginx/html/img/bonus.png" failed (2: No such file or directory), client: 91.219.54.65, server: localhost, request: "GET /img/bonus.png HTTP/1.1", host: "doc.dts.pp.ua", referrer: "http://doc.dts.pp.ua/css/all.css"
static_1    | 2017/08/11 19:59:21 [error] 5#5: *15 open() "/usr/share/nginx/html/img/oneciconcloud.png" failed (2: No such file or directory), client: 91.219.54.65, server: localhost, request: "GET /img/oneciconcloud.png HTTP/1.1", host: "doc.dts.pp.ua", referrer: "http://doc.dts.pp.ua/css/all.css"
`
пошло что-то не так. Или я чего-тот не понимаю?

**Comment by VladyslavKurmaz** [comment]
@SashkaNebesny 
на сейчас:
* создана первичная конфигурация для nginx (apache использовался как начальная тестовая площадка, если будут запросы - сделаю конфиг и для apache)
* есть шаг генерации свмоподписных сертификатов для https
...
Ошибка переместилась на уровень nginx - Java backend, смотрю что там не так
