### ISSUE TITLE
Used DBs

### ISSUE THREAD

**Issue by VladyslavKurmaz** [Papka24/base#6]
I'm trying to build docker-compose setup
From source code and logs I can see references to
* Apache Cassandra
```
tried: localhost/127.0.0.1:9042
```
* postgresql
```
jdbc.driver=org.postgresql.Driver
```
* ScyllaDB
```
scylla.path=localhost
```
* Redis
```
redis.path=localhost
```
Should I deploy and configure all 4 DBs?
Thanks!

**Comment by MaximBelov** [comment]
I set 4 DBs  up.  And then it was start without errors.

**Comment by VladyslavKurmaz** [comment]
@MaximBelov 
Thanks!
...
Where can I define cassandra host name?
tried: localhost/127.0.0.1:9042
config.properties has no properties with cassandra substring in the name

**Comment by MaximBelov** [comment]
@VladyslavKurmaz 
try

docker run -p 127.0.0.1:9042:9042 -i -t scylladb/scylla

base/server/src/main/resources/config.properties

scylla.path=localhost
scylla.keyspace=papka24
scylla.port=9042
scylla.enable=true

**Comment by VladyslavKurmaz** [comment]
@MaximBelov 
With docker-compose use localhost is not a case.
As you can see scylla starts listening 9042 port, but server tries to connect to 127.0..0.1
```
scylla.path=scylla
scylla.keyspace=papka24
scylla.enable=true
```
Looks like server couldn't local file with properties 
![image](https://user-images.githubusercontent.com/1977961/27601478-352022d0-5b78-11e7-93c7-96641a8530f0.png)

**Comment by VladyslavKurmaz** [comment]
@MaximBelov 
Looks like, server for some reasons couldn't read parameters from config.properties
Once I hardcode scylla docker-compose DNS name
```
     scyllaPath = "scylla";//Main.property.getProperty("scylla.path");
```
server starts working fine.

---
I run server using next command
```
java -jar /home/papka-24.jar
```
Can this cause an error during reading parameters from config.properties?

**Comment by VladyslavKurmaz** [comment]
I added simple output for one of the property and got next log:

com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1:9042] **Cannot connect), localhost/127.0.0.1:9042** 

INFO: Scanning for root resource and provider classes in the packages:
  ua.papka24.server.api
**server.domain: 95.85.56.80**

I can assume that server tries to connect to the scylla before properties are read.

**Comment by MaximBelov** [comment]
1. Create postgress base papka24

2. Create user papka24

3. Replace in file server/src/main/resources/sql/CreateDB.sql
GRANT SELECT ON ALL TABLES IN SCHEMA public TO papka24_ro;
with 
GRANT SELECT ON ALL TABLES IN SCHEMA public TO papka24;

4. Import from CreateDB.sql 

5. docker run -p 127.0.0.1:9042:9042 -i -t scylladb/scylla
INFO  2017-06-27 21:47:48,896 [shard 0] storage_service - Starting listening for CQL clients on 172.17.0.2:9042...

6. server/src/main/resources/config.properties
scylla.path=172.17.0.2
Recompile jar-file
gradle shadowJar;

7. Start your server 
java -jar papka-170624.jar

<iframe src="https://giphy.com/embed/xUOrvYi2HKQtXEPUKQ" width="480" height="204" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/xUOrvYi2HKQtXEPUKQ">via GIPHY</a></p>

**Comment by VladyslavKurmaz** [comment]
@MaximBelov 
Thanks!.
Postgres db issue is fixed now.
...
I will raise scylla issue in separate ticket.
...
This issue can be closed.
